### ISSUE TITLE
Doesn´t seem to work for Xcode 6.3.1 (latest)

### ISSUE THREAD

**Issue by kolien** [Keithbsmiley/PlaygroundQuickLook#4]
Due to different folder structure and file names?

**Comment by keith** [comment]
Thanks, yep! I'll get to this soon. Feel free to submit a PR if you'd like to fix it!

**Comment by keith** [comment]
Apparently I forgot to create a new release after fixing this a while ago, I've pushed that now https://github.com/keith/PlaygroundQuickLook/releases/tag/0.1.2
